from abobuilder import AboBuilder, clean_multiline
import numpy as np
import os
from pyqint import MoleculeBuilder, HF, FosterBoys

def main():
    # perform Hartree-Fock calculation of CO
    co = MoleculeBuilder().from_name('CO')
    res = HF(co, basis='sto3g').rhf(verbose=True)

    desc = clean_multiline("""
        This file contains the canonical molecular orbitals of CO, calculated
        using the program PyQInt (https://ifilot.github.io/pyqint/) using a
        STO-3g basis set.
                           
        This file has been generated by Abobuilder (https://github.com/ifilot/abobuilder).
    """)

    occupied_colors = [
        np.array([0.2, 0.7, 0.9]),  # positive lobe
        np.array([0.1, 0.4, 0.6]),  # negative lobe
    ]
    unoccupied_colors = [
        np.array([0.9, 0.4, 0.2]),
        np.array([0.7, 0.2, 0.1]),
    ]

    builder = AboBuilder(
        occupied_colors=occupied_colors,
        unoccupied_colors=unoccupied_colors,
    )

    # construct .abo file for the canonical orbitals of CO
    if not os.path.exists('co.abo'):
        builder.build_abo_hf_v1('co.abo', 
                                res['nuclei'], 
                                res['cgfs'], 
                                res['orbc'], 
                                res['orbe'],
                                nsamples=51,
                                compress=True,
                                geometry_descriptor=desc)

    # perform Foster-Boys localization
    res_fb = FosterBoys(res).run()

    desc = clean_multiline("""
        This file contains the localized molecular orbitals of CO, calculated
        using the program PyQInt (https://ifilot.github.io/pyqint/) using a
        STO-3g basis set. The localization has been done using the Foster-Boys
        method.
                           
        This file has been generated by Abobuilder (https://github.com/ifilot/abobuilder).
    """)

    # construct .abo file for the localized orbitals of CO
    if not os.path.exists('co_fb.abo'):
        builder.build_abo_hf_v1('co_fb.abo', 
                                res['nuclei'], 
                                res_fb['cgfs'], 
                                res_fb['orbc'], 
                                res_fb['orbe'],
                                nsamples=51,
                                compress=True,
                                geometry_descriptor=desc)

if __name__ == '__main__':
    main()