import sys
import os

from abobuilder import AboBuilder, clean_multiline
from pyqint import MoleculeBuilder, HF, FosterBoys

def main():
    # perform Hartree-Fock calculation of ethylene
    ethylene = MoleculeBuilder().from_name('ethylene')
    res = HF(ethylene, basis='sto3g').rhf(verbose=True)
    
    desc = clean_multiline("""
        This file contains the canonical molecular orbitals of ethylene, calculated
        using the program PyQInt (https://ifilot.github.io/pyqint/) using a
        STO-3g basis set.
                           
        This file has been generated by Abobuilder (https://github.com/ifilot/abobuilder).
    """)

    # CH4nstruct .abo file for the canonical orbitals of CH4
    if not os.path.exists('ethylene.abo'):
        AboBuilder().build_abo_hf_v1('ethylene.abo', 
                                res['nuclei'], 
                                res['cgfs'], 
                                res['orbc'], 
                                res['orbe'],
                                nsamples=71,
                                compress=True,
                                geometry_descriptor=desc)

    # perform Foster-Boys localization
    res_fb = FosterBoys(res).run()

    desc = clean_multiline("""
        This file contains the localized molecular orbitals of ethylene, calculated
        using the program PyQInt (https://ifilot.github.io/pyqint/) using a
        STO-3g basis set. The localization has been done using the Foster-Boys
        method.
                           
        This file has been generated by Abobuilder (https://github.com/ifilot/abobuilder).
    """)

    # Construct .abo file for the localized orbitals of ethylene
    if not os.path.exists('ethylene_fb.abo'):
        AboBuilder().build_abo_hf_v1('ethylene_fb.abo', 
                                res['nuclei'], 
                                res_fb['cgfs'], 
                                res_fb['orbc'], 
                                res_fb['orbe'],
                                nsamples=71,
                                compress=True,
                                geometry_descriptor=desc)

if __name__ == '__main__':
    main()
